// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGODPkd7FHT-TwpRGBckg2MJBrDgZBPZs',
    appId: '1:983874925443:web:92e2861de869a613fc7cb6',
    messagingSenderId: '983874925443',
    projectId: 'app4-5bd95',
    authDomain: 'app4-5bd95.firebaseapp.com',
    storageBucket: 'app4-5bd95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9-GSW6GUZAbBxap-uJScaYQLCpPrNgYE',
    appId: '1:983874925443:android:e5de08a8c17ff415fc7cb6',
    messagingSenderId: '983874925443',
    projectId: 'app4-5bd95',
    storageBucket: 'app4-5bd95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhl2kBztuYTdx6QveTmTLP85Jh1CCkK54',
    appId: '1:983874925443:ios:8c41bf670c4cc7f9fc7cb6',
    messagingSenderId: '983874925443',
    projectId: 'app4-5bd95',
    storageBucket: 'app4-5bd95.firebasestorage.app',
    iosBundleId: 'com.example.aiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhl2kBztuYTdx6QveTmTLP85Jh1CCkK54',
    appId: '1:983874925443:ios:8c41bf670c4cc7f9fc7cb6',
    messagingSenderId: '983874925443',
    projectId: 'app4-5bd95',
    storageBucket: 'app4-5bd95.firebasestorage.app',
    iosBundleId: 'com.example.aiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGODPkd7FHT-TwpRGBckg2MJBrDgZBPZs',
    appId: '1:983874925443:web:6f9e351a697ed5b1fc7cb6',
    messagingSenderId: '983874925443',
    projectId: 'app4-5bd95',
    authDomain: 'app4-5bd95.firebaseapp.com',
    storageBucket: 'app4-5bd95.firebasestorage.app',
  );
}
